### ISSUE TITLE
Clarify purpose of the project

### ISSUE THREAD

**Issue by davelab6** [TiroTypeworks/Nutso#5]
Is this project's purpose to serve as a technical example for others to reimplement, or is it intended as a permissively licensed font source to be directly integrated into other font projects?

**Comment by tiroj** [comment]
Both. I used Noto outlines in the font files specifically so people would be free to make any use they wanted of all the files, but I assume most people will want to copy the .fea code or the lookups in the .vtp files.

**Comment by davelab6** [comment]
> I used Noto outlines in the font files specifically so people would be free to make any use they wanted of all the files

I think the Apache license doesn't really permit this, because it requires that the full text of the license is given to everyone who receives a copy of the work, even works that include Apache licensed that are licensed under other terms. The MIT and BSD licenses are the same in this regard, and while they are shorter and so less burdensome, I'm not sure that any of these are a good fit for what you want to do.

**Comment by tiroj** [comment]
As I recall, I included the Apache license with the Nutso stuff simply because that was the license under which the Noto fonts were then released. A one line license that says 'Do whatever you want with this stuff' would suit me fine.

**Comment by davelab6** [comment]
That's what I mean - everything that takes anything from Noto inherits the requirements of the Apache license to give a copy of that license to each recipient, even if the thing is overall licensed under other terms. 

CC-0 is as close as you can legally get to that.

**Comment by tiroj** [comment]
Hmm. In this case, the only Noto aspect is the outlines in the demo font, and that's the only thing I would presume has to be covered by the Apache license, i.e. the only part of Nutso that I don't think anyone wants or needs to use.

David, I'm travelling at the moment, and my laptop has died. I wonder if you can help me sort out the appropriate licensing for Nutso, in terms of making clear that the Apache bit refers only to the Noto in the demo fonts, and not to any of the .fea or .vtp etc., which is all font-independent and can be CC-0.

If that's too complicated, I'd make another demo font using non-Noto outlines that can also be CC-0 without the Apache license attachment.

**Comment by davelab6** [comment]
Sure I'll send a pull request

**Comment by davelab6** [comment]
(I assume the VTP file doesn't have any Noto data, I don't have a windows VM to hand to confirm)

**Comment by tiroj** [comment]
Correct. The .vtp is a plain text file containing the VOLT lookups and group definitions.
