### ISSUE TITLE
Issue while exporting

### ISSUE THREAD

**Issue by V6037** [TiroTypeworks/Nutso#7]
Hello ! I'm new around, I love the work you've done with Nutso, I would use it for my diploma project but each time I want to export the font from Glyphs (by opening the Nutso2 file with the latest Glyphs app) numbers are not aligned any more
<img width="209" alt="Capture d’écran 2019-05-30 à 13 42 48" src="https://user-images.githubusercontent.com/48881085/58630813-d5a29d00-82e0-11e9-873a-ae6d25f03350.png">
and this just by exporting it.

Do you maybe have an good advice for me ? 

Thanks a lot for your work and time, 
Leo.

**Comment by tiroj** [comment]
Note that the font files in the repo are provided only as an example implementation with compiled OpenType Layout tables. If you decompile the OTF or TTF font file in Glyphs or another font tool it is very likely that the GSUB and GPOS layout information will not be correctly decompiled, so what you would need to do is copy the Nutso2.fea code into the font editor, replacing whatever decompiled code has been inserted, and then try compiling.

[I've not personally tried this, and the .fea code was provided by @miguelsousa based on my MS VOLT .vtp implementation.]

**Comment by V6037** [comment]
Wow thank you for your answer. I don't understand what GSUB or GPOS are but
I get that I have to keep the .fea code of Nutso and switch it with my
export.

Thanks a lot.

Leo

Le jeu. 30 mai 2019 à 19:14, John Hudson <notifications@github.com> a
écrit :
